import type { Plan } from "@/features/ledger/types";

export const demoPlan: Plan = {
  user: { id: "demo-user", name: "Huzaifa", email: "huzaifa@example.com" },
  totals: [{ currency: "PKR", oweMinor: 240000, owedMinor: 110000 }],
  groups: [
    {
      id: "weekend-crew",
      name: "Weekend crew",
      currency: "PKR",
      accent: "#6657E8",
      balanceMinor: -240000,
      role: "owner",
      members: [
        { id: "demo-user", name: "Huzaifa", email: "huzaifa@example.com" },
        { id: "sara", name: "Sara", email: "sara@example.com" },
        { id: "hamza", name: "Hamza", email: "hamza@example.com" },
      ],
    },
    {
      id: "flat-bills",
      name: "Flat bills",
      currency: "PKR",
      accent: "#E88B3D",
      balanceMinor: 110000,
      role: "member",
      members: [
        { id: "demo-user", name: "Huzaifa", email: "huzaifa@example.com" },
        { id: "hamza", name: "Hamza", email: "hamza@example.com" },
      ],
    },
  ],
  reviews: [
    {
      id: "review-1",
      groupId: "flat-bills",
      debtor: { id: "hamza", name: "Hamza", email: "hamza@example.com" },
      recipient: { id: "demo-user", name: "Huzaifa", email: "huzaifa@example.com" },
      amountMinor: 110000,
      currency: "PKR",
      status: "awaiting_review",
      eventName: "September internet",
      eventDate: "2026-09-05",
      note: "Bank transfer",
      createdAt: "2026-09-12T11:32:00.000Z",
    },
  ],
  activity: [
    {
      id: "activity-1",
      icon: "send",
      title: "Hamza says he paid",
      detail: "Rs 1,100 · Flat bills",
      createdAt: "2026-09-12T11:32:00.000Z",
      tone: "warning",
    },
    {
      id: "activity-2",
      icon: "file-text",
      title: "Dinner at Monal",
      detail: "Rs 6,000 split with 3 friends",
      createdAt: "2026-09-11T19:10:00.000Z",
      tone: "neutral",
    },
    {
      id: "activity-3",
      icon: "check-circle",
      title: "Fuel settled",
      detail: "Sara confirmed Rs 2,400",
      createdAt: "2026-09-10T15:20:00.000Z",
      tone: "positive",
    },
  ],
  transactions: [
    {
      id: "personal-1",
      source: "personal",
      title: "Coffee money",
      eventDate: "2026-09-13",
      amountMinor: 185000,
      currency: "PKR",
      direction: "outgoing",
      kind: "expense",
      counterparty: "Ali",
      status: "open",
      createdAt: "2026-09-13T08:20:00.000Z",
    },
    {
      id: "expense-1",
      source: "group",
      groupId: "weekend-crew",
      groupName: "Weekend crew",
      title: "Dinner at Monal",
      eventDate: "2026-09-11",
      amountMinor: 240000,
      currency: "PKR",
      direction: "outgoing",
      kind: "expense",
      counterparty: "Sara",
      createdAt: "2026-09-11T19:10:00.000Z",
    },
    {
      id: "personal-2",
      source: "personal",
      title: "Camera loan",
      eventDate: "2026-09-08",
      amountMinor: 1200000,
      currency: "PKR",
      direction: "incoming",
      kind: "loan",
      counterparty: "Ali",
      status: "settled",
      settledAt: "2026-09-10T17:45:00.000Z",
      createdAt: "2026-09-08T17:45:00.000Z",
    },
    {
      id: "expense-2",
      source: "group",
      groupId: "flat-bills",
      groupName: "Flat bills",
      title: "September internet",
      eventDate: "2026-09-05",
      amountMinor: 110000,
      currency: "PKR",
      direction: "incoming",
      kind: "expense",
      createdAt: "2026-09-05T12:00:00.000Z",
    },
  ],
};
